#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  1 16:22:37 2017

@author: Jennifer Jennings
"""

import numpy as np
import cv2

# Load in Gray Scale
pic = cv2.imread('cat.png', 0)

# 

threshold_value = 150

(T_value,binary_threshold) = cv2.threshold(pic, threshold_value, 255,cv2.THRESH_BINARY)

# pix less than (threshold_value) 200 will be white, otherwise black


cv2.imshow('Image',pic)
cv2.imshow('Binary', binary_threshold) # black and white image

cv2.waitKey(0)
cv2.destroyAllWindows()
