#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  1 15:59:07 2017

@author: Jennifer Jennings
"""

# Draw with cv2

import numpy as np
import cv2

# Step 1:
pic = np.zeros((500,500,3), dtype = 'uint8' ) # 500 x 500 pix, 3 channels

# Step 2 ( rectangle) :
cv2.rectangle(pic, (0,0), (500,150), 
               (156,100,98), 3, 
               lineType = 50, shift =0)
# Ancor to pic, start point, end point, col, channel, line, min 

# Step 2: (line):
    
cv2.line(pic, (350, 350), (500,350), (0,0,255))

# Step 2: (circle)
colour = (255,0,255)
cv2.circle(pic, (250,250), 150, colour)

# Step 3 (text)
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(pic, 'UDEMY', (100,100), 
            font, 3, (255,255,255), 4, cv2.LINE_8)

# ancor = pic, text = 'UDEMY', cords = (100), font, size of text,
# colour, thickness of letters = 4 , type of line = cv2.LINE_8



    
# View drawing:     

cv2.imshow('dark',pic)

cv2.waitKey(0)
cv2.destroyAllWindows()


