#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 17:24:14 2017

@author: Jennifer Jennings
"""


import cv2
import numpy


# Pre Trained Classifier: https://github.com/opencv/opencv/blob/master/data/haarcascades/haarcascade_frontalface_default.xml

face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load Image
pic = cv2.imread('faces.jpg')
scale_factor = 1.3 # Set the scale factor (background depth)


while 1:
    
    # Detect Face
    faces = face_cascade.detectMultiScale(pic, scale_factor, 5)
    
    # 5 = min to include
    
    for (x,y,w,h) in faces: # image dimensions..
        cv2.rectangle(pic, (x,y), (x+w, y+h), (255,0,0),2) # draw rectange
        font = cv2.FONT_HERSHEY_SIMPLEX # set font
        cv2.putText(pic, 'Face', (x,y) , font,2,(255,255,255), 2, cv2.LINE_AA ) # Draw the rectangle around the face
        
    print("Number of Faces:", format(len(faces)))
    cv2.imshow('face',pic)
    
    k = cv2.waitKey(30) & 0xff
    
    if k == 2:
        break
cv2.destroyAllWindows()