#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct  4 14:30:59 2017

@author: Jennifer Jennings
"""

import numpy as np
import cv2

# img = cv2.imread('flower.jpg') read in image


# img = cv2.imread('flower.jpg',0) read in image with greyscale

# img = cv2.imread('flower.jpg',1) read in image with full colour 

# img = cv2.imread('flower.jpg',-1) read in image with alpha channel colour 

img = cv2.imread('flower.jpg',0)

cv2.imshow('Original',img)
cv2.waitKey(0)

cv2.destroyAllWindows()