#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  1 16:18:00 2017

@author: Jennifer Jennings
"""


import cv2
import numpy as np

# read in image
pic = cv2.imread('flower.jpg')

cols = pic.shape[1]
rows = pic.shape[0]

center = (cols/2,rows/2)
angle = 90

M = cv2.getRotationMatrix2D(center, angle, 0.5)
# 1 = scale
# 

rotate = cv2.warpAffine(pic, M, (cols, rows))
cv2.imshow('Rotated',rotate)

cv2.waitKey(0)
cv2.destroyAllWindows()