#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Dec  5 16:53:48 2017

@author: Jennifer Jennings
"""
import cv2
import numpy 


# Laod movie
movie = cv2.VideoCapture("sample.mp4")

# Play original video clip by clip
while (movie.isOpened() ):
    ret, frame = movie.read()
    cv2.imshow('vid', frame)
    
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
    
movie.release()
cv2.destroyAllWindows()


# Save movie as an avi
fourcc = cv2.VideoWriter_fourcc(*'XVID')
fps = 30 # frames per second
frame_size = (720,480)#
out = cv2.VideoWriter('converted_sample.avi', fourcc, fps, frame_size)

